__title__ = 'tg2web'
__description__ = 'Telegram channel render to web'
__url__ = 'tg.bmpi.dev'
__version__ = "0.0.1"
__python_version__ = '3.7.3'
__author__ = 'Dawei Ma'
__author_email__ = 'bmpidev@gmail.com'
__license__ = 'MIT LICENSE'
__copyright__ = 'Copyright 2020 BMPI.dev'